apiVersion: apps/v1
kind: Deployment
metadata:
  name: vitrine
  labels:
    app: vitrine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vitrine
  template:
    metadata:
      labels:
        app: vitrine
      annotations:
        ad.datadoghq.com/app.logs: '[{"source":"nginx","service":"vitrine"}]'
    spec:
      containers:
        - name: app
          image: app
          ports:
            - containerPort: 8080
